# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phone_book.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10phone_book.proto\x1a\x1bgoogle/protobuf/empty.proto\"*\n\rDeleteRequest\x12\x19\n\x07\x63ontact\x18\x01 \x01(\x0b\x32\x08.Contact\"*\n\rSearchRequest\x12\x19\n\x07\x63ontact\x18\x01 \x01(\x0b\x32\x08.Contact\"a\n\x07\x43ontact\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x12\n\npatronymic\x18\x04 \x01(\t\x12\x0c\n\x04note\x18\x05 \x01(\t\"\'\n\tPhoneBook\x12\x1a\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x08.Contact2\xa8\x01\n\x10PhoneBookService\x12.\n\naddContact\x12\x08.Contact\x1a\x16.google.protobuf.Empty\x12+\n\rsearchContact\x12\x0e.SearchRequest\x1a\x08.Contact0\x01\x12\x37\n\rdeleteContact\x12\x0e.DeleteRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phone_book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DELETEREQUEST']._serialized_start=49
  _globals['_DELETEREQUEST']._serialized_end=91
  _globals['_SEARCHREQUEST']._serialized_start=93
  _globals['_SEARCHREQUEST']._serialized_end=135
  _globals['_CONTACT']._serialized_start=137
  _globals['_CONTACT']._serialized_end=234
  _globals['_PHONEBOOK']._serialized_start=236
  _globals['_PHONEBOOK']._serialized_end=275
  _globals['_PHONEBOOKSERVICE']._serialized_start=278
  _globals['_PHONEBOOKSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
