# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import phone_book_pb2 as phone__book__pb2


class PhoneBookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addContact = channel.unary_unary(
                '/PhoneBookService/addContact',
                request_serializer=phone__book__pb2.Contact.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.searchContact = channel.unary_stream(
                '/PhoneBookService/searchContact',
                request_serializer=phone__book__pb2.SearchRequest.SerializeToString,
                response_deserializer=phone__book__pb2.Contact.FromString,
                )
        self.deleteContact = channel.unary_unary(
                '/PhoneBookService/deleteContact',
                request_serializer=phone__book__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class PhoneBookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhoneBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addContact': grpc.unary_unary_rpc_method_handler(
                    servicer.addContact,
                    request_deserializer=phone__book__pb2.Contact.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'searchContact': grpc.unary_stream_rpc_method_handler(
                    servicer.searchContact,
                    request_deserializer=phone__book__pb2.SearchRequest.FromString,
                    response_serializer=phone__book__pb2.Contact.SerializeToString,
            ),
            'deleteContact': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteContact,
                    request_deserializer=phone__book__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhoneBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhoneBookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBookService/addContact',
            phone__book__pb2.Contact.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def searchContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PhoneBookService/searchContact',
            phone__book__pb2.SearchRequest.SerializeToString,
            phone__book__pb2.Contact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhoneBookService/deleteContact',
            phone__book__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
